export const jobItems = [
  {
    id: 1,
    image: "/images/jobImages/job1.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Engineering",
  },
  {
    id: 2,
    image: "/images/jobImages/job2.jpg",
    alt: "Team working",
    desc: "3 open positions",
    title: "Product",
  },
  {
    id: 3,
    image: "/images/jobImages/job3.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Marketing",
  },
  {
    id: 4,
    image: "/images/jobImages/job4.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Big data Science",
  },
  {
    id: 5,
    image: "/images/jobImages/job5.jpg",
    alt: "Team working",
    title: "Cloud Platform",
  },
  {
    id: 6,
    image: "/images/jobImages/job6.jpg",
    alt: "Team working",
    desc: "11 open positions",
    title: "Art",
  },
  {
    id: 7,
    image: "/images/jobImages/job7.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Art",
  },
  {
    id: 8,
    image: "/images/jobImages/job8.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Art",
  },
  {
    id: 9,
    image: "/images/jobImages/job9.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Art",
  },
  {
    id: 10,
    image: "/images/jobImages/job10.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Art",
  },
  {
    id: 11,
    image: "/images/jobImages/job11.jpg",
    alt: "Team working",
    desc: "4 open positions",
    title: "Art",
  },
];
